# NumPy: Arrays and Vectorized Computation

In [2]:
import numpy as np
np.random.seed(12345)
import matplotlib.pyplot as plt
plt.rc("figure", figsize=(10, 6))
np.set_printoptions(precision=4, suppress=True)

In [9]:
my_arr = np.arange(1000000)
print(my_arr[:5])

[0 1 2 3 4]


In [10]:
my_list = list(range(1000000))
my_list[:5]

[0, 1, 2, 3, 4]

# The NumPy ndarray: A Multidimensional Array Object

In [12]:
# Generate some random data
data = np.random.randn(2, 3)
data

array([[-0.2047,  0.4789, -0.5194],
       [-0.5557,  1.9658,  1.3934]])

In [13]:
data.shape

(2, 3)

In [15]:
data.dtype

dtype('float64')

### Creating ndarrays

In [17]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [18]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [19]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [21]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

### Basic Indexing and Slicing

In [24]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
arr[5]

5

In [26]:
arr[5:8]

array([5, 6, 7])

In [28]:
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [29]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
arr2d[2]

array([7, 8, 9])

In [31]:
arr2d[2,1]

8

### Boolean Indexing

In [34]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)

In [35]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [37]:
data[names == 'Bob']

array([[ 0.05  ,  0.6702,  0.853 , -0.9559],
       [ 1.0015, -0.5031, -0.6223, -0.9212]])

In [39]:
data[data < 0] = 0
data

array([[0.05  , 0.6702, 0.853 , 0.    ],
       [0.    , 0.    , 0.    , 0.    ],
       [0.    , 1.0746, 0.7236, 0.69  ],
       [1.0015, 0.    , 0.    , 0.    ],
       [0.    , 0.2229, 0.0513, 0.    ],
       [0.8167, 0.4336, 1.0107, 1.8249],
       [0.    , 0.8506, 0.    , 0.9124]])

### Transposing Arrays

In [40]:
arr = np.arange(15).reshape(3,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [41]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [42]:
arr = np.random.randn(6, 3)
arr

array([[ 0.1882,  2.1695, -0.1149],
       [ 2.0037,  0.0296,  0.7953],
       [ 0.1181, -0.7485,  0.585 ],
       [ 0.1527, -1.5657, -0.5625],
       [-0.0327, -0.929 , -0.4826],
       [-0.0363,  1.0954,  0.9809]])

In [43]:
arr = np.random.randn(7) * 5
arr

array([-2.9474,  7.9085, -2.6437,  2.285 ,  4.6498, -7.8464, -5.1124])

A ufunc can return multiple arrays. modf is one example 
it returns the fractional and integral parts of a floating point array

In [52]:
remainder, whole_part = np.modf(arr)
print(remainder)
print(whole_part)

[-0.9474  0.9085 -0.6437  0.285   0.6498 -0.8464 -0.1124]
[-2.  7. -2.  2.  4. -7. -5.]


Suppose we wanted to take a value from xarr whenever the corresponding value in cond is True otherwise take the value from yarr.
With np.where you can write this very concisely

In [49]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

In [51]:
np.where(cond, xarr, yarr)

array([1.1, 2.2, 1.3, 1.4, 2.5])

The second and third arguments to np.where don’t need to be arrays; one or both of
them can be scalars. A typical use of where in data analysis is to produce a new array of
values based on another array. Suppose you had a matrix of randomly generated data
and you wanted to replace all positive values with 2 and all negative values with -2.
This is very easy to do with np.where:

In [53]:
arr = np.random.randn(4, 4)
arr

array([[-0.4028,  0.2205, -0.1934,  0.6692],
       [-1.649 , -2.2528, -1.1668,  0.3536],
       [ 0.7021, -0.2746, -0.1391,  0.1077],
       [-0.6065, -0.4171, -0.017 , -1.2241]])

In [54]:
arr > 0

array([[False,  True, False,  True],
       [False, False, False,  True],
       [ True, False, False,  True],
       [False, False, False, False]])

In [55]:
np.where(arr > 0, 2, -2)

array([[-2,  2, -2,  2],
       [-2, -2, -2,  2],
       [ 2, -2, -2,  2],
       [-2, -2, -2, -2]])

In [56]:
np.where(arr > 0, 2, arr) # set only positive values to 2

array([[-0.4028,  2.    , -0.1934,  2.    ],
       [-1.649 , -2.2528, -1.1668,  2.    ],
       [ 2.    , -0.2746, -0.1391,  2.    ],
       [-0.6065, -0.4171, -0.017 , -1.2241]])

### Mathematical and Statistical Methods

In [57]:
arr = np.random.randn(5, 4)
arr

array([[-1.8008,  1.6347,  0.989 ,  0.4579],
       [ 0.5552,  1.3067, -0.4406, -0.3014],
       [ 0.4988, -0.824 ,  1.3206,  0.508 ],
       [-0.6534,  0.187 , -0.3917, -0.2723],
       [-0.0171,  0.6803,  0.6355, -0.7572]])

In [60]:
print(arr.mean())
print(np.mean(arr))
print(arr.sum())

0.16575924410092605
0.16575924410092605
3.315184882018521


In [61]:
print(arr.mean(axis=1))
print(arr.sum(axis=0))

[ 0.3202  0.28    0.3758 -0.2826  0.1354]
[-1.4175  2.9848  2.1128 -0.3649]


### Methods for Boolean Arrays

In [63]:
arr = np.random.randn(100)
(arr > 0).sum() # Number of positive values

44

### Sorting

In [64]:
arr = np.random.randn(6)
arr

array([-1.0767, -0.1925, -0.8712,  0.4209, -1.2114, -0.2589])

In [66]:
arr.sort()
arr

array([-1.2114, -1.0767, -0.8712, -0.2589, -0.1925,  0.4209])

In [67]:
large_arr = np.random.randn(1000)
large_arr.sort()
large_arr[int(0.05 * len(large_arr))] # 5% quantile

-1.5308984278773312

### Unique and Other Set Logic

In [68]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [69]:
ints = np.array([3, 3, 3, 2, 2, 1, 1, 4, 4])
np.unique(ints)

array([1, 2, 3, 4])

Another function, np.in1d, tests membership of the values in one array in another,
returning a boolean array

In [71]:
values = np.array([6, 0, 0, 3, 2, 5, 6])
np.in1d(values, [2, 3, 6])

array([ True, False, False,  True,  True, False,  True])

### Linear Algebra

In [72]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [73]:
y = np.array([[6., 23.], [-1, 7], [8, 9]])
y

array([[ 6., 23.],
       [-1.,  7.],
       [ 8.,  9.]])

In [74]:
x.dot(y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [75]:
np.dot(x, y)

array([[ 28.,  64.],
       [ 67., 181.]])

### Pseudorandom Number Generation

The numpy.random module supplements the built-in Python random with functions for efficiently generating whole arrays of sample values from many kinds of probability distributions. For example, you can get a 4 by 4 array of samples from the standard
normal distribution using normal

In [76]:
samples = np.random.normal(size = (4, 4)) # multiple arrays from a normal distribution with mean = 0 and std = 1
samples

array([[ 0.5732,  0.1933,  0.4429,  1.2796],
       [ 0.575 ,  0.4339, -0.7658, -1.237 ],
       [-0.5367,  1.8545, -0.92  , -0.1082],
       [ 0.1525,  0.9435, -1.0953, -0.144 ]])

In [81]:
arr_from_normal = np.random.normal(75, 4, size=(4, 4)) # multiple arrays from a normal distribution with mean = 75 and std = 4
arr_from_normal

array([[73.2422, 76.1568, 76.2719, 75.1431],
       [79.1375, 72.9723, 79.9146, 70.6814],
       [68.9853, 74.3306, 74.2644, 70.9877],
       [73.8291, 71.6776, 73.914 , 78.3023]])